/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */

/* 지출 */
interface ExpenseEntity {
    /* 지출 SEQ */
    seq: number

    /* 지출 카테고리 SEQ */
    ctgSeq: number

    /* 금액 */
    amount: number

    /* 지출일 */
    expenseAt: Date

    /* 비고 */
    cmt?: string | null

    /* 추가 정보 */
    options?: string | null

    /* 수정시간 */
    updatedAt?: Date | null
}

type ExpenseEntityCreation = PartialK<ExpenseEntity, 'seq'>

interface ExpenseCategoryEntity {
    /** 지출 카테고리 SEQ */
    seq: number
    /** 지출 카테고리 명 */
    name: string
    /** 추가정보 */
    options?: object
}

/* 제품/단위 맵핑 */
interface ProductEntity {
    /* 제품 정보 SEQ */
    prdInfoSeq: number

    /* 단위 SEQ */
    unitSeq: number

    /* 단위수량 목록 */
    unitCntList?: number[] | null

    /* 제품정보 */
    prdInfo: ProductInfoEntity
    /* 단위 */
    unit: UnitEntity
}

/* 지출 제퓸 */
interface ExpenseProductEntity {
    /* 지출 Seq */
    expsSeq: number

    /* 제품 SEQ */
    prdSeq: number

    /* 수량 */
    cnt: number

    /* 가격 */
    price: number

    /* 단위수량 */
    unitCnt?: number | null

    /* 비고 */
    cmt?: string | null
}

interface ExpenseProductExt extends ExpenseProductEntity {
    product: ProductExt
}

/* 메뉴 */
interface MenuEntity {
    /* 메뉴 Seq */
    seq: number

    /* 메뉴 카테고리 Seq */
    ctgSeq: number

    /* 메뉴 명 */
    name: string

    /* 이름 약어 */
    abv?: string | null

    /* 가격 */
    price: number

    /* 비고 */
    cmt?: string | null

    /* 추가정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null
}

type MenuEntityCreation = PartialK<MenuEntity, 'seq'>

/* 메뉴 카테고리 */
interface MenuCategoryEntity {
    /* 메뉴 카테고리 Seq */
    seq: number

    /* 메뉴 카테고리 명 */
    name: string

    /* 추가정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null
}

type MenuCategoryEntityCreation = PartialK<MenuCategoryEntity, 'seq'>

/* 주문 */
interface MyOrderEntity {
    /* 주문 Seq */
    seq: number

    /* 매장 Seq */
    storeSeq: number

    /* 총 금액 */
    amount: number

    /* READY: 준비, COOKED: 조리 완료, PAID: 결제 완료 */
    status?: 'READY' | 'COOKED' | 'PAID'

    /* 주문 시간 */
    orderAt?: Date

    /* 조리완료 시간 */
    cookedAt?: Date | null

    /* 비고 */
    cmt?: string | null

    /* 수정시간 */
    updatedAt?: Date
}

type MyOrderEntityCreation = PartialK<MyOrderEntity, 'seq'>

interface Order extends MyOrderEntity {
    orderMenues: OrderMenu[]
    payments: PaymentEntity[]
    store: StoreEntity
}

/* 주문 메뉴 */
interface OrderMenuEntity {
    /* 메뉴 Seq */
    menuSeq: number

    /* 주문 Seq */
    orderSeq: number

    /* 가격 menu는 가격이 바뀔수가 있음 */
    price: number

    /* 수량 */
    cnt: number
}

type OrderMenuEntityCreation = PartialK<OrderMenuEntity, 'orderSeq'>

interface OrderMenu extends OrderMenuEntity {
    menu: MenuEntity
}

/* 주문 메뉴 예약 */
interface OrderMenuRsvEntity {
    /* 메뉴 Seq */
    menuSeq: number

    /* 주문예약 Seq */
    orderRsvSeq: number

    /* 가격 menu는 가격이 바뀔수가 있음 */
    price: number

    /* 수량 */
    cnt: number
}

/* 주문 예약 */
interface OrderRsvEntity {
    /* 주문예약 Seq */
    seq: number

    /* 매장 Seq */
    storeSeq: number

    /* 총 금액 */
    amount: number

    /* HH:MM */
    rsvTime: string

    /* 요일 */
    dayType?: 'MON' | 'TUE' | 'WED' | 'THU' | 'FRI' | 'SAT' | 'SUN' | null

    /* 비고 */
    cmt?: string | null

    /* 추가정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null
}

type OrderRsvEntityCreation = PartialK<OrderRsvEntity, 'seq'>

/* 결재 */
interface PaymentEntity {
    /* 결재 Seq */
    seq: number

    /* 주문 Seq */
    orderSeq: number

    /* 결재 금액 */
    amount: number

    /* CASH: 현금, CARD: 카드 */
    payType?: 'CASH' | 'CARD'

    /* 지급날짜 */
    payAt: Date
}

type PaymentEntityCreation = PartialK<PaymentEntity, 'seq'>

/* 장소 카테고리 */
interface PlaceCategoryEntity {
    /* 장소 카테고리 Seq */
    seq: number

    /* 장소 카테고리 명 */
    name: string

    /* 비고 */
    cmt?: string | null

    /* 추가정보 */
    options?: string | null
}

type PlaceCategoryEntityCreation = PartialK<PlaceCategoryEntity, 'seq'>

/* 제품 */
interface ProductEntity {
    /* SEQ */
    seq: number

    /* 제품 SEQ */
    prdInfoSeq: number

    /* 단위 SEQ */
    unitSeq: number

    /* 단위수량 목록 */
    unitCntList?: number[] | null
}

type ProductCreationEntity = PartialK<ProductEntity, 'prdInfoSeq' | 'unitSeq'>

interface ProductExt extends ProductEntity {
    unit: UnitEntity
    prdInfo: ProductInfoEntity
}

/* 제품 정보 */
interface ProductInfoEntity {
    /* 제품 Seq */
    seq: number

    /* 식자재 Seq */
    suplSeq: number

    /* 식자재 명 */
    name: string

    /* 비고 */
    cmt?: string | null

    /* 추가 정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null

    /* 제품목록 */
    products: RequiredK<ProductExt, 'unit'>[]
}

type ProductInfoCreationEntity = PartialK<ProductInfoEntity, 'seq' | 'products'>
/* 설정 */
interface SettingEntity {
    /* 설정 Seq */
    seq: number

    /* 설정 정보 */
    config: SettingConfig
}

interface SettingConfig {
    menuCtgOrders?: { seq: number; order: number }[]
    menuOrders?: { seq: number; order: number }[]
    storeCtgOrders?: { seq: number; order: number }[]
    storeOrders?: { seq: number; order: number }[]
}

/* 매장 */
interface StoreEntity {
    /* 매장 Seq */
    seq: number

    /* 매장 카테고리 Seq */
    ctgSeq: number

    /* 장소 카테고리 Seq */
    placeCtgSeq?: number | null

    /* 매장 명 */
    name: string

    /* 기타 정보 */
    cmt?: string | null

    /* 위도 */
    latitude?: number | null

    /* 경도 */
    longitude?: number | null

    /* 추가정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null
}

type StoreCategoryEntityCreation = PartialK<StoreCategoryEntity, 'seq'>

/* 매장 카테고리 */
interface StoreCategoryEntity {
    /* 매장 카테고리 Seq */
    seq: number

    /* 장소 카테고리 Seq */
    placeCtgSeq?: number | null

    /* 매장 카테고리 명 */
    name: string

    /* 추가정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null
}

/* 매장 지출 로그 */
interface StoreExpenseLogEntity {
    /* 매장 지출 로그 Seq */
    seq: number

    /* 매장 Seq */
    storeSeq: number

    /* 지출일 */
    expenseAt: Date

    /* 비고 */
    cmt: string
}

/* 식자재 */
interface SupplyEntity {
    /* 식자재 Seq */
    seq: number

    /* 식자재 명 */
    name: string

    /* 추가 정보 */
    options?: string | null

    /* 생성시간 */
    createdAt?: Date | null

    /* 수정시간 */
    updatedAt?: Date | null
}

type SupplyEntityCreation = PartialK<SupplyEntity, 'seq'>

/* 단위 */
interface UnitEntity {
    /* 단위 SEQ */
    seq: number

    /* 단위명 */
    name: string

    /* 단위수량 여부 */
    isUnitCnt: boolean
}

interface QueryParam {
    expand: string
}
